#!/bin/bash
# ~/.dmenurc

## define the font for dmenu to be used
DMENU_FN="Iosevka-8"

## background colour for unselected menu-items
DMENU_NB="#121312"

## textcolour for unselected menu-items
DMENU_NF="#3F4F5D"

## background colour for selected menu-items
DMENU_SB="#121312"

## textcolour for selected menu-items
DMENU_SF="#43AAE5"

## command for the terminal application to be used:
TERMINAL_CMD="terminator -e"

## export our variables
DMENU_OPTIONS="-fn $DMENU_FN -nb $DMENU_NB -nf $DMENU_NF -sf $DMENU_SF -sb $DMENU_SB"
export DMENU_FN DMENU_NB DMENU_NF DMENU_SF DMENU_SB DMENU_OPTIONS TERMINAL
